package com.syntrace.entity;

/**
 * Canonical event taxonomy produced by the normalizer, independent of log vendor.
 */
public enum EventType {
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_FAILURE,
    ACCOUNT_LOCKOUT,
    PRIVILEGE_ESCALATION,
    PROCESS_CREATION,
    SCRIPT_EXECUTION,
    UNKNOWN_EXECUTABLE,
    SERVICE_INSTALLED,
    SCHEDULED_TASK_CREATED,
    REGISTRY_MODIFICATION,
    USB_DEVICE_CONNECTED,
    USB_DEVICE_DISCONNECTED,
    FILE_ACCESS,
    FILE_CREATED,
    FILE_DELETED,
    FILE_ENCRYPTED,
    MASS_FILE_ACCESS,
    NETWORK_CONNECTION,
    SMB_CONNECTION,
    FIREWALL_ALLOW,
    FIREWALL_DENY,
    DNS_QUERY,
    DATA_TRANSFER,
    SECURITY_TOOL_DISABLED,
    ANTIVIRUS_ALERT,
    AUDIT_LOG_CLEARED,
    CONFIGURATION_CHANGE,
    SYSTEM_START,
    SYSTEM_SHUTDOWN,
    OTHER
}
